### PR TITLE
add pyinstaller to linux environment

### PR DESCRIPTION
**Pull request by lawndoc**
Added Python, PyInstaller, and UPX to the Linux environment in the Dockerfile so the one container is capable of cross-platform builds.

It would also be cool to do the same thing with [darling](https://github.com/darlinghq/darling) to be able to build Python executables for *any* major target OS. That is outside the scope of this PR, but I'm curious to hear your thoughts on that idea.

### CODE REVIEW

**Comment by lawndoc** [comment]
Oops sorry I think I need to fix something. I'll submit a commit later, I've gotta go for a while.

**Comment by lawndoc** [comment]
I must have forgotten to test the checksum step. I added that last.

**Comment by lawndoc** [comment]
Aha, Python 3.10 and 3.11 source files need a different public key in the keyring. I also was messing up the directories because I forgot how Docker builds work (whoops). I should have a working version shortly.

**Comment by TobiX** [comment]
I'm sorry, but I'd rather not. I like to keep the scope of this container to serve the one purpose documented in the README. There are plenty of other containers to base a Linux Python build environment on (for example the Python manylinux containers) and there are a lot of ways to use multiple containers in one build (multi-stage Dockerfiles, multiple steps in your CI workflows, etc.)

**Comment by lawndoc** [comment]
That's fair. Thanks for the feedback and suggested alternatives.

**Pull request closed without merging**
